[project]
name = "restaurant-webscraper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "apify-client>=2.1.0",
    "ipykernel>=6.30.1",
    "pandas>=2.3.3",
    "selenium>=4.35.0",
    "webdriver-manager>=4.0.2",
]
